### ISSUE TITLE
GeoLite Legacy databases were discontinued on January 2, 2019

### ISSUE THREAD

**Issue by Atavic** [KPN-CISO/netchecker#1]
The [GeoIPURL](https://github.com/KPN-CISO/netchecker/blob/master/netchecker.py#L9) redirects to https://dev.maxmind.com/geoip/geoip2/geolite2/

Also the GeoIPURLzip, GeoIP for csv are now delivered in a different way:
https://geolite.maxmind.com/download/geoip/database/GeoLite2-ASN-CSV.zip

Downloaded file has a *date format* in the name. Hope it helps.

**Comment by uforia** [comment]
Thanks for letting me know; I'll investigate and patch this ASAP.

**Comment by uforia** [comment]
Netchecker has been rewritten to handle the new GeoLite formats from MaxMind. Let me know how it works for you.
